/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_AxleTypeInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_AxleTypeInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BedTypeInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BedTypeInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BodyStyleInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BodyStyleInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BrakeInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BrakeInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_CabTypeInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_CabTypeInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_DriveTypeInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_DriveTypeInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_EngineInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_EngineInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_ManufacturerBodyCodeInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_ManufacturerBodyCodeInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_SpringInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_SpringInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_SteeringInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_SteeringInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_TransmissionInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_TransmissionInfo';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_VehicleCountry } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_VehicleCountry';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_VehicleSubModel } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_VehicleSubModel';
import type { MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_WheelBaseInfo } from './MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_WheelBaseInfo';

export type MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_AttributeContainer = {
    AxleTypes?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_AxleTypeInfo>;
    BedTypes?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BedTypeInfo>;
    BodyStyles?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BodyStyleInfo>;
    Brakes?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_BrakeInfo>;
    CabTypes?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_CabTypeInfo>;
    Countries?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_VehicleCountry>;
    DriveTypes?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_DriveTypeInfo>;
    Engines?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_EngineInfo>;
    ManufacturerBodyCodes?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_ManufacturerBodyCodeInfo>;
    Springs?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_SpringInfo>;
    Steering?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_SteeringInfo>;
    SubModels?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_VehicleSubModel>;
    Transmissions?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_TransmissionInfo>;
    Wheel?: Array<MOTOR_DaaS_WebServices_DTO_Information_VehicleInfo_Attributes_WheelBaseInfo>;
};
